root = "."
testdata_dir = "testdata"
tmp_dir = "temp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 1000
exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "testdata",
    "uploads",
    "thunder-tests",
]
exclud_file = []
exclud_regex = ["_test.go"]
exclud_unchanged = false
follower_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmp", "html", "env"]
kill_delay = "0s"
log = "build-error.log"
send_interupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clean_on_rebuild = false
